# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

USER_LIB_PATH   += $(HOME)/git/tool-avrlib

BOARD_TAG    	= uno
ARDUINO_LIBS 	= Wire SPI TimerOne Adafruit_ADS1015 Min

ARDUINO_DIR     = /usr/share/arduino

include $(HOME)/git/Arduino-Makefile/Arduino.mk
