# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    	= uno

ARDUINO_DIR   	= /Applications/Arduino.app/Contents/Java

include $(HOME)/Documents/development/git/Arduino-Makefile/Arduino.mk
